sudo: required

language: java

jdk:
  - openjdk11

services:
  - docker

install: true

script:
  - ./gradlew cloneHalExplorer
  - ./gradlew -p subprojects/hal-explorer build
  - ./gradlew build
  - cd subprojects/backend
  - ../../gradlew createDockerfile
  - cd build
  - docker build -t kaitoedter/chatty .
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/chatty
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker tag kaitoedter/chatty registry.heroku.com/chatty42/web
  - docker push registry.heroku.com/chatty42/web
#  - docker login -u dockersvc -p $OPENSHIFT_TOKEN_DEV registry.horizon-dev.siemens.io
#  - docker tag kaitoedter/chatty registry.horizon-dev.siemens.io/demos/chatty
#  - docker push registry.horizon-dev.siemens.io/demos/chatty
  - cd ../../..
  - ./heroku-container-release.sh
